### PR TITLE
[fix] Added DOCKER_TAG variable for version pinning to match intended release version

### LINKED ISSUE #554: [bug] docker-compose uses 'latest' tags; should use version numbers
**Describe the bug**
Using `latest` tags in docker-compose can cause unwanted upgrades if using `docker compose pull` instead of `make pull` (which pulls the correct image and tag them as latest). This may accidentally pull incompatible versions and break a working deployment unexpectedly. This is especially risky for users running older or stable releases (for example, 24.11), because pulling will download newer images (e.g., 25.10.1) without warning.

**Steps To Reproduce**
1. Deploy using docker-compose for a specific release (e.g., 24.11)
2. Run `docker compose pull`
3. Docker downloads images tagged as `latest` (typically the newest release)
4. Deployment may break due to incompatibility or unexpected updates

**Expected behavior**
Images should always match the intended release version in the compose file, avoiding accidental upgrades or mismatches regardless of command usage.

**Screenshots**
N/A

**System Informatioon:**
- OS: Any
- Docker version: Any
- Browser and Browser Version (if applicable): N/A
- Additional context: The workflow currently relies on `make pull` to determine and overwrite the tags as `latest`, but this is not a reliable safeguard against accidental upgrades.

### PR DESCRIPTION
**Pull request by atif09**
this change introduces a DOCKER_TAG environment variable that allows users to pin specific image versions in .env file, both 'docker compose pull' and 'make pull' now work according to this variable, ensuring consistent version behavior across all deployment methods

## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [x] I have manually tested the changes proposed in this pull request.
- [ ] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [x] I have updated the documentation.

## Reference to Existing Issue

Closes #554.

## Description of Changes

- Add DOCKER_TAG=latest to .env file
- Update all OpenWISP image tags in docker-compose.yml to use ${DOCKER_TAG:-latest}
- Update Makefile to include .env and use DOCKER_TAG when retagging images

## Screenshot
version pinning test:

**with `DOCKER_TAG=25.10.0` in .env**
image

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -1,6 +1,9 @@
 # Find documentation in README.md under
 # the heading "Makefile Options".
 
+include .env
+export
+
```
Comment (atif09) [inline Makefile]: ive added a blank line here which I'll delete

File: Makefile [hunk 2]
```diff
@@ -20,7 +23,7 @@ pull:
 				 'openwisp-freeradius' 'openwisp-nginx' 'openwisp-openvpn' 'openwisp-postfix' \
 				 'openwisp-websocket' ; do \
 		docker pull --quiet $(USER)/$${image}:$(TAG); \
-		docker tag  $(USER)/$${image}:$(TAG) openwisp/$${image}:latest; \
+		docker tag  $(USER)/$${image}:$(TAG) openwisp/$${image}:$${DOCKER_TAG:-latest}; \
```
Comment (pandafy) [inline Makefile]: This means, we will always have versioned tagged images.

File: deploy/auto-install.sh [hunk 3]
```diff
@@ -87,7 +87,7 @@ download_docker_openwisp() {
 		rm -rf $INSTALL_PATH &>>$LOG_FILE
 	fi
 	if [ -z "$GIT_BRANCH" ]; then
-		if [[ "$openwisp_version" == "edge" ]]; then
+		if [[ "$openwisp_version" == "edge" || "$openwisp_version" == "latest" ]]; then
```
Comment (pandafy) [inline deploy/auto-install.sh]: If we do this, then there will be no different in edge and latest tags.

File: Makefile [hunk 4]
```diff
@@ -1,7 +1,10 @@
 # Find documentation in README.md under
 # the heading "Makefile Options".
 
-OPENWISP_VERSION = 25.10.0
+include .env
+export
```
Comment (pandafy) [inline Makefile]: Why do we need to export the environment variables? The docker compose should automatically read the OPENWISP_VERSION from the .env file.

File: Makefile [hunk 5]
```diff
@@ -19,8 +22,9 @@ pull:
 	for image in 'openwisp-base' 'openwisp-nfs' 'openwisp-api' 'openwisp-dashboard' \
 				 'openwisp-freeradius' 'openwisp-nginx' 'openwisp-openvpn' 'openwisp-postfix' \
 				 'openwisp-websocket' ; do \
-		docker pull --quiet $(USER)/$${image}:$(TAG); \
-		docker tag  $(USER)/$${image}:$(TAG) openwisp/$${image}:latest; \
+				version=$${OPENWISP_VERSION:-edge}; \
+				docker pull --quiet $(USER)/$${image}:$${version}; \
+				docker tag  $(USER)/$${image}:$${version} openwisp/$${image}:$${version}; \
```
Comment (pandafy) [inline Makefile]: Indentation is off!

File: docker-compose.yml [hunk 6]
```diff
@@ -12,7 +12,7 @@ x-celery-depends-on: &celery-depends-on
 
 services:
   dashboard:
-    image: openwisp/openwisp-dashboard:latest
+    image: openwisp/openwisp-dashboard:${OPENWISP_VERSION:-edge}
```
[the remark this answers is not in the document]
Comment (nemesifier) [reply docker-compose.yml]: @pandafy ok, I think we need to open another issue for that.

File: .env [hunk 7]
```diff
@@ -4,6 +4,9 @@
 # Essential
 DASHBOARD_DOMAIN=dashboard.openwisp.org
 API_DOMAIN=api.openwisp.org
+# Image tag pinning
+IMAGE_OWNER=openwisp
+OPENWISP_VERSION=edge
```
[the remark this answers is not in the document]
Comment (atif09) [reply .env]: the `edge` default is intentional and consistent with `TAG = edge` which is already defined in this file. this change does not produce any new behavior

users deploying to production are expected to override `OPENWISP_VERSION` in their own .env to a specific release tag

File: Makefile [hunk 8]
```diff
@@ -41,11 +45,13 @@ base-build:
 	             $$BUILD_ARGS; \
 	docker build --tag openwisp/openwisp-base:latest \
 	             --file ./images/openwisp_base/Dockerfile ./images/ \
-	             $$BUILD_ARGS
+	             $$BUILD_ARGS; \
+	docker tag openwisp/openwisp-base:latest $(IMAGE_OWNER)/openwisp-base:$(OPENWISP_VERSION)
```
[the remark this answers is not in the document]
Comment (atif09) [reply Makefile]: without this `docker tag` ,  the `$(IMAGE_OWNER)/openwisp-base:$(OPENWISP_VERSION)` never exists and `publish` fails
